# Generated by Django 5.1.8 on 2025-07-06 00:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('assign', 'Assigned'), ('remove', 'Removed')], help_text='Type of action performed', max_length=20)),
                ('entity_type', models.CharField(choices=[('business', 'Business'), ('transaction', 'Transaction'), ('category', 'Category'), ('user_role', 'User Role')], help_text='Type of entity affected', max_length=20)),
                ('entity_id', models.PositiveIntegerField(help_text='ID of the affected entity')),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('business', models.ForeignKey(blank=True, help_text='Business this action relates to', null=True, on_delete=django.db.models.deletion.CASCADE, to='business_api.business')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Sales, Rent, Utilities)', max_length=100)),
                ('type', models.CharField(choices=[('income', 'Income Category'), ('expense', 'Expense Category'), ('both', 'Both Income & Expense')], default='both', help_text='Whether this category is for income, expense, or both', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='business_api.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Whether this is income or expense', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (must be positive)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(help_text='Date when transaction occurred')),
                ('description', models.TextField(help_text='Description of the transaction')),
                ('reference_number', models.CharField(blank=True, help_text='Optional reference number (invoice #, receipt #, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text="Soft delete flag - don't permanently delete transactions")),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this transaction was deleted', null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='business_api.business')),
                ('created_by', models.ForeignKey(help_text='User who created this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_transactions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_transactions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Transaction category', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transaction_api.transactioncategory')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
